/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.Barang;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import repository.BarangRepository;
import util.DateUtil;

/**
 *
 * @author adzaz
 */
public class DialogTambahBarang extends Dialog {
    private String fileName;
    BarangRepository BarangRepo = new BarangRepository();
    DateUtil dateUtil = new DateUtil();
    /**
     * Creates new form DialogTambahBarang
     */
    public DialogTambahBarang(JFrame frame) {
        super(frame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHarga = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        btnTambah = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btnTambahFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHarga.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtHarga.setBorder(null);
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 290, 40));

        txtNama.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtNama.setBorder(null);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 380, 40));

        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 160, 40));

        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 160, 40));
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 200));

        btnTambahFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahFotoMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambahFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/tambah barang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        closeMessage();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try {
            String nama = txtNama.getText();
            int harga = Integer.valueOf(txtHarga.getText());
            String newpath = "src/fotoBarang";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdir();
            }
            File fileAwal = null;
            File fileAkhir = null;
            String ext = this.fileName.substring(fileName.lastIndexOf('.')+1);
            fileAwal = new File(fileName);
            fileAkhir = new File(newpath+"/"+nama+dateUtil.timeNowImage()+"."+ext);
     
            
            Barang barang = new Barang( nama, 0, harga, fileAkhir.toString());
            
            if(BarangRepo.add(barang)){
                System.out.println("Berhasil");
                 Files.copy(fileAwal.toPath(), fileAkhir.toPath());
                closeMessage();
            }else{
                System.out.println("gagal");
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnTambahFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahFotoMouseClicked
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image img = icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon ic = new ImageIcon(img);
            lblFoto.setIcon(ic);
            fileName = f.getAbsolutePath();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnTambahFotoMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JLabel btnTambahFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
