/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.Pemesanan;
import entity.Presensi;
import javax.swing.JFrame;
import java.awt.Color;
/**
 *
 * @author adzaz
 */
public class DialogAturPresensi extends Dialog {

    /**
     * Creates new form DialogAturPresensi
     */
    public DialogAturPresensi(JFrame frame) {
        super(frame);
        initComponents();
        setValue();
    }
    public void setValue(){
        String start = Presensi.StartPresensi;
        String late = Presensi.LatePresensi;
        String end = Presensi.EndPresensi;
        String [] arrayStart= start.split(":", 5);
        String [] arrayLate= late.split(":", 5);
        String [] arrayEnd= end.split(":", 5);
        txtStartJam.setText(arrayStart[0]);
        txtStartMenit.setText(arrayStart[1]);
        txtStartDetik.setText(arrayStart[2]);
        txtLateJam.setText(arrayLate[0]);
        txtLateMenit.setText(arrayLate[1]);
        txtLateDetik.setText(arrayLate[2]);
        txtEndJam.setText(arrayEnd[0]);
        txtEndMenit.setText(arrayEnd[1]);
        txtEndDetik.setText(arrayEnd[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEndJam = new javax.swing.JTextField();
        txtEndMenit = new javax.swing.JTextField();
        txtEndDetik = new javax.swing.JTextField();
        txtLateJam = new javax.swing.JTextField();
        txtLateMenit = new javax.swing.JTextField();
        txtLateDetik = new javax.swing.JTextField();
        txtStartDetik = new javax.swing.JTextField();
        txtStartMenit = new javax.swing.JTextField();
        txtStartJam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 30, 30));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 140, 30));

        txtEndJam.setBackground(new Color(0,0,0,0));
        txtEndJam.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtEndJam.setBorder(null);
        txtEndJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndJamActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 40, 30));

        txtEndMenit.setBackground(new Color(0,0,0,0));
        txtEndMenit.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtEndMenit.setBorder(null);
        getContentPane().add(txtEndMenit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 40, 30));

        txtEndDetik.setBackground(new Color(0,0,0,0));
        txtEndDetik.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtEndDetik.setBorder(null);
        getContentPane().add(txtEndDetik, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 40, 30));

        txtLateJam.setBackground(new Color(0,0,0,0));
        txtLateJam.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtLateJam.setBorder(null);
        txtLateJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLateJamActionPerformed(evt);
            }
        });
        getContentPane().add(txtLateJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 40, 30));

        txtLateMenit.setBackground(new Color(0,0,0,0));
        txtLateMenit.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtLateMenit.setBorder(null);
        getContentPane().add(txtLateMenit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 40, 30));

        txtLateDetik.setBackground(new Color(0,0,0,0));
        txtLateDetik.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtLateDetik.setBorder(null);
        txtLateDetik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLateDetikActionPerformed(evt);
            }
        });
        getContentPane().add(txtLateDetik, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 40, 30));

        txtStartDetik.setBackground(new Color(0,0,0,0));
        txtStartDetik.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtStartDetik.setBorder(null);
        getContentPane().add(txtStartDetik, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 40, 30));

        txtStartMenit.setBackground(new Color(0,0,0,0));
        txtStartMenit.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtStartMenit.setBorder(null);
        getContentPane().add(txtStartMenit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 40, 30));

        txtStartJam.setBackground(new Color(0,0,0,0));
        txtStartJam.setFont(new java.awt.Font("Quicksand Bold", 0, 24)); // NOI18N
        txtStartJam.setBorder(null);
        txtStartJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartJamActionPerformed(evt);
            }
        });
        getContentPane().add(txtStartJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/atur waktu presensi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        closeMessage();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String end = txtEndJam.getText()+":"+txtEndMenit.getText()+":"+txtEndDetik.getText();
        String start = txtStartJam.getText()+":"+txtStartMenit.getText()+":"+txtStartDetik.getText();
        String late = txtLateJam.getText()+":"+txtLateMenit.getText()+":"+txtLateDetik.getText();
        
        Presensi.StartPresensi = start;
        Presensi.EndPresensi = end;
        Presensi.LatePresensi = late;
        closeMessage();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtStartJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartJamActionPerformed

    private void txtLateJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLateJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLateJamActionPerformed

    private void txtEndJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndJamActionPerformed

    private void txtLateDetikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLateDetikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLateDetikActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEndDetik;
    private javax.swing.JTextField txtEndJam;
    private javax.swing.JTextField txtEndMenit;
    private javax.swing.JTextField txtLateDetik;
    private javax.swing.JTextField txtLateJam;
    private javax.swing.JTextField txtLateMenit;
    private javax.swing.JTextField txtStartDetik;
    private javax.swing.JTextField txtStartJam;
    private javax.swing.JTextField txtStartMenit;
    // End of variables declaration//GEN-END:variables
}
