/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.Barang;
import entity.BarangMasuk;
import entity.DetailPengeluaran;
import entity.Pengeluaran;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import repository.BarangMasukRepository;
import repository.BarangRepository;
import repository.PengeluaranRepository;
import util.DateUtil;
import view.main.maindasboard;
import view.swing.Notification;

/**
 *
 * @author adzaz
 */
public class DIalogTambahStok extends Dialog {
    BarangRepository barangRepo = new BarangRepository();
    BarangMasukRepository barangMasukRepo = new BarangMasukRepository();
    private List<Barang> listBarang = new ArrayList<>();
    private int grandTotal = 0;
    DateUtil dateUtil = new DateUtil();
    /**
     * Creates new form DIalogTambahJamaah
     */
    public DIalogTambahStok(JFrame frame) {
        super(frame);
        initComponents();
        fillComboBoxBarang();
    }
    public void setValue(){
        lblTotal.setText(String.valueOf(grandTotal));
    }
    
   private void loadTable(){
        try {
             DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");      
            model.addColumn("Nama");
            model.addColumn("Harga");
            model.addColumn("Jumlah");
            model.addColumn("Sub total");

           int no = 1;
             for(Barang res:listBarang){
                model.addRow(new Object[]{
                    res.getId(),
                    res.getNama(),
                    res.getHarga(),
                    res.getStok(),
                    res.getSubTotal(),
                    
           });
            
    }
           table.setModel(model);
        } catch (Exception e) {
            
        }
    }

    private void fillComboBoxBarang(){
        for(Barang br:barangRepo.get()){
           cmbBarang.addItem(br.getId()+", "+br.getNama()+", Stok = "+br.getStok());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbBarang = new view.pallet.ComboBoxSuggestion();
        checkSemua = new javax.swing.JCheckBox();
        txtJumlahStok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new view.pallet.Table();
        lblTotal = new javax.swing.JLabel();
        lblBatal = new javax.swing.JLabel();
        lblTambah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(cmbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 310, 40));
        getContentPane().add(checkSemua, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 113, -1, -1));

        txtJumlahStok.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        getContentPane().add(txtJumlahStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 60, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 50, 50));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 390, 370));

        lblTotal.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 220, 40));

        lblBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBatalMouseClicked(evt);
            }
        });
        getContentPane().add(lblBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 160, 30));

        lblTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTambahMouseClicked(evt);
            }
        });
        getContentPane().add(lblTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/tambah stok barang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 589));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
             int jumlahStok = Integer.valueOf(txtJumlahStok.getText());
        String str = String.valueOf(cmbBarang.getSelectedItem());
        String [] getId= str.split(",", 2);
        int id = Integer.valueOf(getId[0]);
        int idBarang = id;
        
        if(checkSemua.isSelected()){
            int gtotal = 0;
            for(Barang br:barangRepo.get()){
                int subTotal = br.getHarga() * Integer.valueOf(txtJumlahStok.getText());
                gtotal += subTotal;
                listBarang.add(new Barang(br.getId(), br.getNama(), jumlahStok, br.getHarga(),subTotal));
            }
            grandTotal = gtotal;
        }else{
            for(Barang br:barangRepo.getById(id)){
                int subTotal = br.getHarga() * Integer.valueOf(txtJumlahStok.getText());
                listBarang.add(new Barang(br.getId(), br.getNama(), jumlahStok, br.getHarga(),subTotal));
            }
            int stotal = 0;
            for(Barang i:listBarang){
                stotal = i.getSubTotal();
            }
        grandTotal += stotal;
        }
        
        
        setValue();
        loadTable();
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lblBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBatalMouseClicked
        closeMessage();
    }//GEN-LAST:event_lblBatalMouseClicked

    private void lblTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahMouseClicked
        maindasboard main =(maindasboard)SwingUtilities.getWindowAncestor(this);
          
        try {
            for(Barang i:listBarang){
                Barang b = new BarangRepository().get(i.getId());
                Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(dateUtil.dateNow());
                BarangMasuk barangMasuk = new BarangMasuk(b, tanggal, i.getStok());
                boolean tambahDetail = barangMasukRepo.add(barangMasuk);
                if(tambahDetail){
            Notification panel = new Notification(main, Notification.Type.SUCCESS, Notification.Location.BOTTOM_RIGHT, "Stok berhasil di tambahkan");
        panel.showNotification();
                }else{
                    
            Notification panel = new Notification(main, Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Gagal menambahkan Stok");
        panel.showNotification();
                }
            }
            closeMessage();
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_lblTambahMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkSemua;
    private view.pallet.ComboBoxSuggestion cmbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBatal;
    private javax.swing.JLabel lblTambah;
    private javax.swing.JLabel lblTotal;
    private view.pallet.Table table;
    private javax.swing.JTextField txtJumlahStok;
    // End of variables declaration//GEN-END:variables
}
