/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.Barang;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import repository.BarangRepository;
import util.DateUtil;
import view.panel.BarangForm;

/**
 *
 * @author adzaz
 */
public class DialogEditBarang extends Dialog {
private String newPath = "";
private int id = BarangForm.id;
    BarangRepository barengRepo = new BarangRepository();
    DateUtil dateUtil = new DateUtil();

    private String Path ;
    /**
     * Creates new form DialogEditBarang
     */
    public DialogEditBarang(JFrame frame) {
        super(frame);
        initComponents();
        setValue();
    }

    public void setValue(){
        for(Barang br:barengRepo.getById(id)){
            txtHarga.setText(String.valueOf(br.getHarga()));
            txtNama.setText(br.getNama());
            txtStok.setText(String.valueOf(br.getStok()));
            try {
                String pathDb = br.getFoto();
                String path = "D:/RahmatanTravel/"+pathDb;
                Path = pathDb;
                File f = new File(path);
                ImageIcon icon = new ImageIcon(f.toString());
                Image image = icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon ic = new ImageIcon(image);
                lblFoto.setIcon(ic);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnTambahFoto = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 200));

        txtStok.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtStok.setBorder(null);
        getContentPane().add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 150, 40));

        txtNama.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtNama.setBorder(null);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 160, 40));

        txtHarga.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtHarga.setBorder(null);
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 290, 40));

        btnTambahFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahFotoMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambahFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 130, 30));

        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 160, 40));

        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/edit barang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahFotoMouseClicked
                 try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image img = icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon ic = new ImageIcon(img);
            lblFoto.setIcon(ic);
            newPath = f.getAbsolutePath();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnTambahFotoMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        closeMessage();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        String nama = String.valueOf(txtNama.getText());
        int harga = Integer.valueOf(txtHarga.getText());
        int stok = Integer.valueOf(txtStok.getText());
        if(newPath.equals("")){
            Barang barang = new Barang(nama, stok, harga, Path);
            barang.setId(id);
            boolean update = barengRepo.update(barang);
            if(update){
                System.out.println("berhasil di update");
                closeMessage();
            }else{
                System.out.println("gagal");
            }
        }else{
            try{
            File sourceFile = new File(Path);
            File fileDelete = new File("D:/RahmatanTravel/"+sourceFile);

            if(fileDelete.exists()){
                boolean deleteImage = fileDelete.delete();
                if(deleteImage){
                    System.out.println("foto berhasil di hapus");
                }else{
                    System.out.println("foto gagal di hapus");
                }
            }
            String pathFolder = "src/upload";
            File fileAwal = null;
            File fileAkhir = null;
            String ext = newPath.substring(newPath.lastIndexOf('.')+1);
            fileAwal = new File(newPath);
            fileAkhir = new File(pathFolder+"/"+nama+dateUtil.timeNow()+"."+ext);
            
            Barang barang = new Barang(nama, stok, harga, Path);
            barang.setId(id);
            boolean update = barengRepo.update(barang);
            if(update){
                System.out.println("Berhasil di update");
                Files.copy(fileAwal.toPath(), fileAkhir.toPath());
                closeMessage();
            }else{
                System.out.println("gagal di update");
            }
            }catch(Exception e){
                    System.out.println(e);
             }
        }
    }//GEN-LAST:event_btnEditMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnTambahFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
