/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.dialog;
import java.awt.Color;
public class dialog_aboutversi extends javax.swing.JFrame {

    /**
     * Creates new form dialog_aboutversi
     */
    public dialog_aboutversi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        keluar = new javax.swing.JLabel();
        developerinformation = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new Color(0,0,0,90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgbutton/silangbutton.png"))); // NOI18N
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        developerinformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgbutton/Developer Information.png"))); // NOI18N
        developerinformation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                developerinformationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                developerinformationFocusLost(evt);
            }
        });
        jPanel1.add(developerinformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 160, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/bg aboutversi.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 119, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 580);

        setSize(new java.awt.Dimension(1024, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void developerinformationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_developerinformationFocusGained
    developerinformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgbutton/Developer Information1.png")));
    }//GEN-LAST:event_developerinformationFocusGained

    private void developerinformationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_developerinformationFocusLost
    developerinformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgbutton/Developer Information.png")));
    }//GEN-LAST:event_developerinformationFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialog_aboutversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialog_aboutversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialog_aboutversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialog_aboutversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dialog_aboutversi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel developerinformation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel keluar;
    // End of variables declaration//GEN-END:variables
}
