/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panel;

/**
 *
 * @author semafie
 */
public class Login1 extends javax.swing.JPanel {

    /**
     * Creates new form Login1
     */
    public Login1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextfield1 = new view.pallet.JTextfield();
        jPasswordfield11 = new view.pallet.JPasswordfield1();
        bg = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, 50));
        jPanel1.add(jPasswordfield11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 190, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/bg login.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 580);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private view.pallet.JPasswordfield1 jPasswordfield11;
    private view.pallet.JTextfield jTextfield1;
    // End of variables declaration//GEN-END:variables
}
